### ISSUE TITLE
Move from Peewee ORM?

### ISSUE THREAD

**Issue by mpope9** [mpope9/nba-sql#10]
Peewee is limited in their backend DB support. Although an agnostic way to do `IGNORE ON DUPLICATE` for multiple DBs seems tricky. Opening this for discussion.

**Comment by avadhanij** [comment]
So I wanted to understand the basis for this issue. What DBs are you targeting, that you feel aren't supported by peewee.

I honestly didn't know about peewee at all. Pretty much the gold standard in Python world is [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy). Although, peewee looks like it's pretty popular too, and is generally easy to start of with for smaller projects.

> However, I do want to move away from peewee and use something like pyodbc, but peewee is too convenient at the moment.

From your comment in the other issue. Are you sure you want to use pyodbc? It's pretty low level, and you will be stuck building the ORM yourself manually, writing every single SQL query.

**Comment by mpope9** [comment]
Fair enough, I was probably targeting Redshift or Greenplum which are both pg based, so PeeWee is probably fine for now. Will leave this open incase there is a strong enough argument made eventually.

**Comment by mpope9** [comment]
Meh, closing this one as PeeWee is good enough.
