### ISSUE TITLE
Allow for enhancement of existing DB with older seasons

### ISSUE THREAD

**Issue by Flavsditz** [mpope9/nba-sql#109]
When I first gave it a try I used the existing bash scripts. It created a new DB filled with data. 
When I went to explore I noticed it was from the latest season only.
I went back to see if I could add another season and got some errors in the process.
I would like to have the opportunity to add older seasons after I have a DB in place.

**Current State:**
Create a DB and populate with data on first creation only.
Subsequently a refresh of data is supported for the latest season

**Enhancement**
Together with the above also add the option to load one or more specific seasons after a DB is initialized

**Requirements**
- It needs to see if a season was already loaded to avoid the extra requests
  - Could be overwritten with a `force` flag
- Need to add an UPSERT capability in the DB

**Comment by mpope9** [comment]
Ah yeah the bash scripts are just for testing. I believe if you use the commandline options then you can achieve what you want using the `--season` flag. Lemme know if that works.
