### ISSUE TITLE
Q: Why the hard limit at the 1997 season?

### ISSUE THREAD

**Issue by Flavsditz** [mpope9/nba-sql#110]
From what I can see the nbastats offers data from the 1970s even... 
Is there a reason to limit the possible fetch to 1997?

Reasons I can think of:
- Size of DB
- Load time due to the initial population of the DB 
  - See open issue #109 for a proposal of something to overcome this by making a request when "one has time"
- Lack of consistency in the data (requires much more data cleaning and handling)
- Limit on request by the NBA api

I couldn't find an explanation on the code or wiki so I am asking here

**Comment by mpope9** [comment]
Hi sorry that I missed this. 97 is the oldest season that the NBA allows to query I believe. Not much else we can do.
