### ISSUE TITLE
Error trying to load all seasons at once

### ISSUE THREAD

**Issue by peopleworks** [mpope9/nba-sql#111]
Hello @mpope9 + Everybody

First, I love this project, is a shame that I am meeting with Python now. 

I have a problem trying to load all seasons at once, I tried in Postgres and SQLite. If I do five is great, but I don't know how to do five by five, because the id keys resets to one. Or somebody has the full database in Postgres and can share it, I think from this point it can be updated with the actual season.

Thanks in advance
Pedro

**Comment by mpope9** [comment]
Hi! Sorry for the late reply. What do you mean five vs five by five? Do you have the screenshot of the GUI or command flags you ran? I don't host any databases

**Comment by peopleworks** [comment]
Hello @mpope9 

Sorry for my bad explanation, If I try to load all seasons at once I get an error, I tried it both SQLite and PostgreSQL, so I test with small groups, and I realized that loading five seasons works great, but if I try to load next group I have the problem that all sequence number in the tables begins in one again.

Thank you so much for your response

**Comment by mpope9** [comment]
That is odd can you post the exact error that you are seeing? Are you using the default mode or current season mode?

**Comment by mpope9** [comment]
Okay I get what is going wrong. There are two game entries instead of a single one:
```
GameEntry(season_id=2024, game_id='0022400147', game_date='2024-11-02T00:00:00', matchup_in='WAS @ MIA', winner='', loser=1610612764)
GameEntry(season_id=2024, game_id='0022400147', game_date='2024-11-02T00:00:00', matchup_in='MIA @ WAS', winner=1610612748, loser='')
```
Where the winner / loser are for some reason reported as different games...? I'll add logic to perform some kind of merge operation before inserting.
