### ISSUE TITLE
Shot chart detail only has made shots

### ISSUE THREAD

**Issue by shaunwhyte** [mpope9/nba-sql#48]
Hey is it possible to make the shot chart details also show missed shots?
Love the work so far!

**Comment by shaunwhyte** [comment]
i looked into the api request and it only returns the made shots so this may be unsolvable for now...

**Comment by shaunwhyte** [comment]
This can be altered to also show  the missed shots, is that something ya'll want?

**Comment by mpope9** [comment]
Hey, good catch I didn't notice that endpoint was only returning made shots. Fixing this would be awesome. I currently don't see how we can get missed shots through the parameters we are passing. Have you been able to trigger missed shots?

**Comment by shaunwhyte** [comment]
I can make a small pull request if you like?

**Comment by mpope9** [comment]
Yes, that'd be very welcome.

**Comment by shaunwhyte** [comment]
Do I need permission to push a branch?

**Comment by mpope9** [comment]
Na, you can fork the repo, create your own branch, then create a PR off of that.

-------- Original Message --------

**Comment by mpope9** [comment]
Fixed by https://github.com/mpope9/nba-sql/pull/49!
