### ISSUE TITLE
Can't run create_postgres.sh on Mac

### ISSUE THREAD

**Issue by sscrewston** [mpope9/nba-sql#83]
I was following the Apache Superset wiki to set up the database with Superset but received this error:

`: line 3: python: command not found`

**Comment by mpope9** [comment]
Were you using a virtual environment and is that environment activated?

**Comment by sscrewston** [comment]
No, I'm on macos. I'm having difficulty running the create_postgres.sh file.

**Comment by mpope9** [comment]
I don't fully understand, but I think this an environment issue. Try creating a new [venv](https://docs.python.org/3/library/venv.html) before running that script.
