### ISSUE TITLE
nba.sql.xz file

### ISSUE THREAD

**Issue by Harry-hash** [mpope9/nba-sql#92]
Hi, Thanks for the great work!

I am wondering where to find the file nba.sql.xz? It seems that I cannot find it in [Releases](https://github.com/mpope9/nba-sql/releases). And could I download the database files as a bunch of sqlite files?

Thank you very much!

**Comment by mvgary094** [comment]
Hey, maybe I'm not very smart but I also can't find that file. Does anyone know where it is?

**Comment by mpope9** [comment]
Sorry I missed this. We don't provide the data, just how to fetch it.
