### ISSUE TITLE
How are we supposed to access the data?

### ISSUE THREAD

**Issue by mvgary094** [mpope9/nba-sql#94]
Hey All,

I have downloaded the data for the 22-23 season but for some reason I cannot figure out how to import it into mysql or sqlite. I'm not sure if I'm supposed to ssh into a docker container, import the data into a mysql server, or query the data with the nba script. Can someone explain what I'm supposed to do with the .db file after I download the data?

CC: @mpope9

**Comment by mpope9** [comment]
Hi. You can open that up with sqlite like this:
```
>sqlite3
SQLite version 3.38.2 2022-03-26 13:51:10
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open nba_sql.db
sqlite> select * from player limit 1;
2544|LeBron James|None|USA|2003|1|1
```

**Comment by mvgary094** [comment]
Thank you for clearing that up!
