### ISSUE TITLE
MySQL Access denied for user 'nba_sql'@'localhost'

### ISSUE THREAD

**Issue by mvgary094** [mpope9/nba-sql#95]
I'm getting the error: Access denied for user 'nba_sql'@'localhost' when I try to push data into an existing mysql db. I ran the docker-compose script and then was able to verify the container worked as expected by going into the container and logging into the mysql db using the following command:  mysql --host=localhost --user=nba_sql --password=nba_sql nba. I tried using 127.0.0.1 but that gives a cannot connect error. 

For context, I found that args.username and password were null so I had to update the code to pass a value. 

I was wondering if anyone had run into this issue and had an idea of how to fix it.

Thanks,
Mike

**Comment by mpope9** [comment]
Hi,

I am not sure what process that you are using, but there is the provided fie: `scripts/create_mysql.sh` that you can run on mac or linux. I'm able to run that script against the MySQL docker container that I've started with:
```
docker-compose -f docker/docker-compose-mysql.yml up -d
```

Does that help at all?

**Comment by mvgary094** [comment]
Yea, I should have put in the exact command but that was the docker-compose script I referenced in my question

**Comment by mvgary094** [comment]
![image](https://github.com/mpope9/nba-sql/assets/72046429/dafdc381-4eb7-4362-9269-af16a434d6a1)

**Comment by mvgary094** [comment]
After running the docker-compose script for mysql that you referenced above, I was able to login to the server and see the nba db. However, I keep getting this error even with the mysql container running

**Comment by mvgary094** [comment]
![image](https://github.com/mpope9/nba-sql/assets/72046429/7d3aad18-776a-4f28-8014-afcb73466956)

**Comment by mvgary094** [comment]
![image](https://github.com/mpope9/nba-sql/assets/72046429/7f10ea79-1a00-4998-ae49-bffd9f588334)

**Comment by mvgary094** [comment]
![image](https://github.com/mpope9/nba-sql/assets/72046429/1077bf16-22e7-4c27-9aa1-cda5e70437ec)

**Comment by mvgary094** [comment]
![image](https://github.com/mpope9/nba-sql/assets/72046429/65ff9f7d-b527-43da-9c52-d0a3a2736902)

**Comment by mvgary094** [comment]
Sorry to spam you with screenshots but I just want to be as transparent as possible. The only modification I made to the compose script was the port number(3306 --> 3307). I'm also running this in pycharm venv if that makes a difference

**Comment by mpope9** [comment]
Try this:
```
set DB_PASSWORD=nba_sql
python stats/nba_sql.py --default-mode --database="mysql" --create-schema --username=nba_sql --database_name=nba --database_host=localhost
```

I've never tried to ran this from the windows cmline, just from the provided application. So what I see missing is the host, username, and password. This doesn't support running the command without using the password as an environment variable and I think the first `set DB_PASSWORD=nba_sql` accomplishes that. The extra commandline args will set the missing fields.

**Comment by mvgary094** [comment]
Alright, I figured out that there was an issue with trying to use a different port number. I think there must be a port setting in peewee that was set by default to 3306. I have removed the container that was listening to 3306 and now I'm getting data flowing in. Thanks a ton for your help and being so quick to respond!

**Comment by mpope9** [comment]
Glad it worked out!
